version: '3.4'

services:
  lognkey.api:
    ports:
      - "5028:80"
    #  - "7051:443"
    image: ${DOCKER_REGISTRY-}lognkeyapi
    #container_name: lognkey-api
    build:
      context: .
      dockerfile: ./LogNKey.API/Dockerfile
    environment:
        "ASPNETCORE_ENVIRONMENT": "Development"
        "ASPNETCORE_URL": "http://localhost"
        "ASPNETCORE_HTTP_PORT": "5028"
        #"ConnectionStrings:Database": "Server=localhost,5432;Database=lognkey;Username=postgres;Password=postgres;Include Error Detail=true"
        "ConnectionStrings:Database": "Host=lognkey.db;Port=5432;Database=lognkey;Username=postgres;Password=postgres;Include Error Detail=true"
        "ConnectionStrings:MessageBroker": "amqp://lognkey-mq:5672"
        "ConnectionStrings:AI": "http://localhost:8000"

  PasswordChecker.ai:
    image: ${DOCKER_REGISTRY-}passwordcheckerai
    container_name: passwordchecker-ai
    build:
      context: .
      dockerfile: Services/PassCheckerService/Dockerfile
    ports:
      - 8008:8000

  lognkey.db:
    image: postgres:latest
    container_name: lognkey-db
    environment:
      - POSTGRES_DB=lognkey
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  lognkey.mq:
    image: rabbitmq:3-management
    container_name: lognkey-mq
    hostname: lognkey-mq
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest